# 향후 판매량 예측 경진대회 모델 성능 개선

- 모델은 똑같이 LightGBM
- 피처 엔지니어링 강화
    1. 베이스라인과 똑같이 피처명 한글화와 데이터 다운캐스팅
    2. 🫧 개별데이터, 즉 `sales_train.csv`, `shops.csv`, `items.csv`, `item_categories.csv`를 활용해 전처리, 파생 피처 생성, 인코딩을 수행
    3. 베이스라인과 동일하게 데이터 조합을 만들자. 이어서 몇 가지 파생 피처를 추가
    4. 테스트 데이터를 합친 후, 2번에서 피처 엔지니어링한 다른데이터들을 병합
    5. 🫧 시차 피처를 만든다. 시차 피처를 만들려면 먼저 '기준 피처별 월간 평균 판매량 피처'를 구해야 함. 이 피처를 기반으로 시차 피처를 만들자.
    6. 🫧 마지막으로 그 외 추가적인 피처 엔지니어링을 적용

In [56]:
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings(action='ignore') # 경고 메시지 생략

# 데이터 경로
data_path = '/kaggle/input/competitive-data-science-predict-future-sales/'

sales_train = pd.read_csv(data_path + 'sales_train.csv')
shops = pd.read_csv(data_path + 'shops.csv')
items = pd.read_csv(data_path + 'items.csv')
item_categories = pd.read_csv(data_path + 'item_categories.csv')
test = pd.read_csv(data_path + 'test.csv')
submission = pd.read_csv(data_path + 'sample_submission.csv')

## 1. 피처 엔지니어링 I : 피처명 한글화와 데이터 다운캐스팅

In [57]:
sales_train = sales_train.rename(columns={'date': '날짜', 
                                          'date_block_num': '월ID',
                                          'shop_id': '상점ID',
                                          'item_id': '상품ID',
                                          'item_price': '판매가',
                                          'item_cnt_day': '판매량'})

shops = shops.rename(columns={'shop_name': '상점명',
                              'shop_id': '상점ID'})

items = items.rename(columns={'item_name': '상품명',
                              'item_id': '상품ID',
                              'item_category_id': '상품분류ID'})

item_categories = item_categories.rename(columns=
                                         {'item_category_name': '상품분류명',
                                          'item_category_id': '상품분류ID'})

test = test.rename(columns={'shop_id': '상점ID',
                            'item_id': '상품ID'})

In [58]:
def downcast(df, verbose=True):
    start_mem = df.memory_usage().sum() / 1024**2
    for col in df.columns:
        dtype_name = df[col].dtype.name
        if dtype_name == 'object':
            pass
        elif dtype_name == 'bool':
            df[col] = df[col].astype('int8')
        elif dtype_name.startswith('int') or (df[col].round() == df[col]).all():
            df[col] = pd.to_numeric(df[col], downcast='integer')
        else:
            df[col] = pd.to_numeric(df[col], downcast='float')
    end_mem = df.memory_usage().sum() / 1024**2
    if verbose:
        print('{:.1f}% 압축됨'.format(100 * (start_mem - end_mem) / start_mem))
    
    return df

all_df = [sales_train, shops, items, item_categories, test]
for df in all_df:
    df = downcast(df)

62.5% 압축됨
38.6% 압축됨
54.2% 압축됨
39.9% 압축됨
70.8% 압축됨

## 2. 피처 엔지니어링 II : 개별 데이터 피처 엔지니어링

- `sales_train.csv`, `shops.csv`, `items.csv`, `item_categories.csv` 데이터를 '각각' 피처 엔지니어링하자

### 2-1. `sales_train.csv` 이상치 제거 및 전처리

- `sales_train.csv` 데이터의 이상치를 제거하고 간단하게 전처리하자.
- 판매가와 판매량 피처의 이상치를 제거하자
    - 이상치가 있으면 성능이 나빠질 우려가 있다.
    - 판매가, 판매량이 음수라면 환불 건이나 오류 ➡️ 이상치로 간주
    - 판매가 0 ~ 50000, 판매량 0 ~ 1000 사이인 데이터만 추출할 것이다.

In [59]:
# 판매가가 0보다 큰 데이터 추출
sales_train = sales_train[sales_train['판매가'] > 0]
# 판매가가 50,000보다 작은 데이터 추출
sales_train = sales_train[sales_train['판매가'] < 50000]

# 판매량이 0보다 큰 데이터 추출
sales_train = sales_train[sales_train['판매량'] > 0]
# 판매량이 1,000보다 작은 데이터 추출
sales_train = sales_train[sales_train['판매량'] < 1000]

- 상점명을 조금 다르게 기입해서 같은 상점인데 따로 기록돼 있는 상점이 있다.
- `shops.csv` 데이터에서 상점명이 유사한 네 쌍을 출력해보자

In [60]:
print(shops['상점명'][0], '||', shops['상점명'][57])
print(shops['상점명'][1], '||', shops['상점명'][58])
print(shops['상점명'][10], '||', shops['상점명'][11])
print(shops['상점명'][39], '||', shops['상점명'][40])

!Якутск Орджоникидзе, 56 фран || Якутск Орджоникидзе, 56
!Якутск ТЦ "Центральный" фран || Якутск ТЦ "Центральный"
Жуковский ул. Чкалова 39м? || Жуковский ул. Чкалова 39м²
РостовНаДону ТРК "Мегацентр Горизонт" || РостовНаДону ТРК "Мегацентр Горизонт" Островной

In [61]:
# sales_train 데이터에서 상점ID 수정
sales_train.loc[sales_train['상점ID'] == 0, '상점ID'] = 57
sales_train.loc[sales_train['상점ID'] == 1, '상점ID'] = 58
sales_train.loc[sales_train['상점ID'] == 10, '상점ID'] = 11
sales_train.loc[sales_train['상점ID'] == 39, '상점ID'] = 40

# test 데이터에서 상점ID 수정
test.loc[test['상점ID'] == 0, '상점ID'] = 57
test.loc[test['상점ID'] == 1, '상점ID'] = 58
test.loc[test['상점ID'] == 10, '상점ID'] = 11
test.loc[test['상점ID'] == 39, '상점ID'] = 40

### 2-2. `shops.csv` 파생 피처 생성 및 인코딩

- 상점명 첫 단어는 상점이 위치한 도시이다.

In [62]:
shops['도시'] = shops['상점명'].apply(lambda x: x.split()[0])

In [63]:
shops['도시'].unique()

array(['!Якутск', 'Адыгея', 'Балашиха', 'Волжский', 'Вологда', 'Воронеж',
       'Выездная', 'Жуковский', 'Интернет-магазин', 'Казань', 'Калуга',
       'Коломна', 'Красноярск', 'Курск', 'Москва', 'Мытищи', 'Н.Новгород',
       'Новосибирск', 'Омск', 'РостовНаДону', 'СПб', 'Самара', 'Сергиев',
       'Сургут', 'Томск', 'Тюмень', 'Уфа', 'Химки', 'Цифровой', 'Чехов',
       'Якутск', 'Ярославль'], dtype=object)

In [64]:
# 느낌표 오타 제거
shops.loc[shops['도시'] =='!Якутск', '도시'] = 'Якутск'

In [65]:
from sklearn.preprocessing import LabelEncoder

# 레이블 인코더 생성
label_encoder = LabelEncoder()
# 도시 피처 레이블 인코딩
shops['도시'] = label_encoder.fit_transform(shops['도시'])

In [66]:
# 상점명 피처 제거
shops = shops.drop('상점명', axis=1)

shops.head()

   상점ID  도시
0     0  29
1     1  29
2     2   0
3     3   1
4     4   2

### 2-3. `items.csv` 파생 피처 생성

- `items.csv`를 활용해 '첫 판매월' 피처를 구해보자

In [67]:
# 상품명 피처 제거
items = items.drop(['상품명'], axis=1)

In [68]:
# 상품이 맨 처음 팔린 날을 피처로 추가
items['첫 판매월'] = sales_train.groupby('상품ID').agg({'월ID': 'min'})['월ID']

items.head()

   상품ID  상품분류ID  첫 판매월
0     0      40   20.0
1     1      76   15.0
2     2      40   19.0
3     3      40   18.0
4     4      40   20.0

In [69]:
items[items['첫 판매월'].isna()]

        상품ID  상품분류ID  첫 판매월
83        83      40    NaN
140      140      45    NaN
168      168      44    NaN
173      173      45    NaN
204      204      44    NaN
...      ...     ...    ...
21974  21974      61    NaN
21975  21975      61    NaN
22022  22022      40    NaN
22035  22035      40    NaN
22137  22137      40    NaN

[368 rows x 3 columns]

- 결측치: 해당 상품이 한 번도 판매된 적이 없다는 뜻
- 2013.01 부터 2015.10 까지 한 번도 팔리지 않은 상품이 있다면 그 상품이 처음 팔린 달을 2015.11로 가정하자
    - 그때도 안 팔릴 수도 있지만 어차피 그러면 테스트 데이터에도 없으니 괜찮다

In [70]:
# 첫 판매월 피처의 결측값을 34로 대체
items['첫 판매월'] = items['첫 판매월'].fillna(34)

### 2-4. `item_categories.csv` 파생 피처 생성 및 인코딩

- 상품분류명의 첫 단어는 범주 대분류
- 큰 범주로 묶으면 범주가 지나치게 세밀할 때보다 성능 향상에 유리

In [71]:
# 상품분류명의 첫 단어를 대분류로 추출
item_categories['대분류'] = item_categories['상품분류명'].apply(lambda x: x.split()[0])

In [72]:
item_categories['대분류'].value_counts()

Игры          14
Книги         13
Подарки       12
Игровые        8
Аксессуары     7
Музыка         6
Программы      6
Карты          5
Кино           5
Служебные      2
Чистые         2
PC             1
Билеты         1
Доставка       1
Элементы       1
Name: 대분류, dtype: int64

In [73]:
def make_etc(x):
    if len(item_categories[item_categories['대분류']==x]) >= 5:
        return x
    else:
        return 'etc'

# 대분류의 고윳값 개수가 5개 미만이면 'etc'로 바꾸기
item_categories['대분류'] = item_categories['대분류'].apply(make_etc)

In [74]:
item_categories.head()

                     상품분류명  상품분류ID         대분류
0  PC - Гарнитуры/Наушники       0         etc
1         Аксессуары - PS2       1  Аксессуары
2         Аксессуары - PS3       2  Аксессуары
3         Аксессуары - PS4       3  Аксессуары
4         Аксессуары - PSP       4  Аксессуары

In [75]:
# 레이블 인코더 생성
label_encoder = LabelEncoder()

# 대분류 피처 레이블 인코딩
item_categories['대분류'] = label_encoder.fit_transform(item_categories['대분류'])

# 상품분류명 피처 제거
item_categories = item_categories.drop('상품분류명', axis=1)

- 지금까지 각 데이터에 적용한 피처 엔지니어링은 다음과 같다

|데이터|적용한 피처 엔지니어링|
|---|---|
|sales_train.csv|* 이상치 제거 <br> * 상품 ID 네 쌍 수정|
|shops.csv|* 상점명 피처를 활용해 도시 피처 새로 추가 <br> * 범주형 데이터인 도시 피처 인코딩 <br> * 상점명 피처 제거|
|items.csv|* 첫 판매월 피처 추가 <br> * 결측값을 34로 대체|
|item_categories.csv|* 대분류 피처 추가 <br> * 고윳값 개수 5개 미만인 대분류 값을 'etc'로 변경 <br> * 대분류 피처 인코딩|

<br>

## 3. 피처 엔지니어링 III : 데이터 조합 및 파생 피처 생성

- 이번에도 데이터 조합을 생성
- 그 다음 월간 판매량, 평균 판매가, 판매건수 피처를 만든다.


### 3-1. 데이터 조합

In [76]:
from itertools import product

train = []
# 월ID, 상점ID, 상품ID 조합 생성
for i in sales_train['월ID'].unique():
    all_shop = sales_train.loc[sales_train['월ID']==i, '상점ID'].unique()
    all_item = sales_train.loc[sales_train['월ID']==i, '상품ID'].unique()
    train.append(np.array(list(product([i], all_shop, all_item))))

idx_features = ['월ID', '상점ID', '상품ID'] # 기준 피처
train = pd.DataFrame(np.vstack(train), columns=idx_features)

### 3-2. 파생 피처 생성

- 이번에는 총 3개의 피처를 새로 만들겠다.
- 월ID, 상점ID, 상품ID 별 '월간 판매량', '평균 판매가' 피처를 만들자

In [77]:
group = sales_train.groupby(idx_features).agg({'판매량': 'sum',
                                               '판매가': 'mean'})
group = group.reset_index()
group = group.rename(columns={'판매량': '월간 판매량', '판매가': '평균 판매가'})

train = train.merge(group, on=idx_features, how='left')

train.head()

   월ID  상점ID   상품ID  월간 판매량  평균 판매가
0    0    59  22154     1.0   999.0
1    0    59   2552     NaN     NaN
2    0    59   2554     NaN     NaN
3    0    59   2555     NaN     NaN
4    0    59   2564     NaN     NaN

- 결측값은 0으로 대체

In [78]:
import gc

# group 변수 가비지 컬렉션
del group
gc.collect();

- 그 다음으로는 '기준 피처별 상품 판매건수' 파생 피처를 만들자

In [79]:
# 상품 판매건수 피처 추가
group = sales_train.groupby(idx_features).agg({'판매량': 'count'})
group = group.reset_index()
group = group.rename(columns={'판매량': '판매건수'})

train = train.merge(group, on=idx_features, how='left')

# 가비지 컬렉션
del group, sales_train
gc.collect()

train.head()

   월ID  상점ID   상품ID  월간 판매량  평균 판매가  판매건수
0    0    59  22154     1.0   999.0   1.0
1    0    59   2552     NaN     NaN   NaN
2    0    59   2554     NaN     NaN   NaN
3    0    59   2555     NaN     NaN   NaN
4    0    59   2564     NaN     NaN   NaN

## 4. 피처 엔지니어링 IV : 데이터 합치기

### 4-1. 테스트 데이터 이어붙이기

In [80]:
# 테스트 데이터 월ID를 34로 설정
test['월ID'] = 34

# train과 test 이어붙이기
all_data = pd.concat([train, test.drop('ID', axis=1)],
                     ignore_index=True,
                     keys=idx_features)
# 결측값을 0으로 대체
all_data = all_data.fillna(0)

all_data.head()

   월ID  상점ID   상품ID  월간 판매량  평균 판매가  판매건수
0    0    59  22154     1.0   999.0   1.0
1    0    59   2552     0.0     0.0   0.0
2    0    59   2554     0.0     0.0   0.0
3    0    59   2555     0.0     0.0   0.0
4    0    59   2564     0.0     0.0   0.0

### 4-2. 모든 데이터 병합

In [81]:
# 나머지 데이터 병합
all_data = all_data.merge(shops, on='상점ID', how='left')
all_data = all_data.merge(items, on='상품ID', how='left')
all_data = all_data.merge(item_categories, on='상품분류ID', how='left')

# 데이터 다운캐스팅
all_data = downcast(all_data)

64.6% 압축됨

In [82]:
# 가비지 컬렉션
del shops, items, item_categories
gc.collect();

## 5. 피처 엔지니어링 V : 시차 피처 생성 ⏱️

- 이번에는 시차 피처를 만들어보자
- **시차 피처(Time lag feature)**: 과거 시점에 관한 피처로, 시계열 성능 향상에 도움이 되는 경우가 많음

<br>

- 시차 피처를 만들려면 기준으로 삼을 피처를 먼저 정해야 한다.
- 이번 경진대회에서는 '월간 평균 판매량'이 좋다
- 때문에 시차 피처를 구하기 전에 '기준 피처별 월간 평균 판매량' 피처를 만들어야 함
- 여러 기준 피처별 월간 평균 판매량 피처를 구한 뒤, 이 피처를 징검다리 삼아 시차 피처를 만들자

### 5-1. 기준 피처별 월간 평균 판매량 파생 피처 생성

- 월간 평균 판매량을 구할 때 기준 피처는 다양하게 정할 수 있다.
    - 예를 들어, 상점별 월간 평균 판매량, 상품별 월간 평균 판매량, 각 상점의 상품별 월간 평균 판매량 등이다.



- 기준 피처로 그룹화해 월간 평균 판매량을 구해주는 함수를 만들어보자
- 파라미터는 총 3개
    - `df`: 작업할 전체 데이터 (DataFrame)
    - `mean_features`: 새로 만든 월간 평균 판매량 파생 피처명을 저장하는 리스트
    - `idx_features`: 기준 피처

In [83]:
def add_mean_features(df, mean_features, idx_features):
    # 기준 피처 확인 
    assert (idx_features[0] == '월ID') and \
           len(idx_features) in [2, 3]
    
    # 파생 피처명 설정 
    if len(idx_features) == 2:
        feature_name = idx_features[1] + '별 평균 판매량'
    else:
        feature_name = idx_features[1] + ' ' + idx_features[2] + '별 평균 판매량'
    
    # 기준 피처를 토대로 그룹화해 월간 평균 판매량 구하기 
    group = df.groupby(idx_features).agg({'월간 판매량': 'mean'})
    group = group.reset_index()
    group = group.rename(columns={'월간 판매량': feature_name})
    
    # df와 group 병합 
    df = df.merge(group, on=idx_features, how='left')
    # 데이터 다운캐스팅 
    df = downcast(df, verbose=False)
    # 새로 만든 feature_name 피처명을 mean_features 리스트에 추가 
    mean_features.append(feature_name)
    
    # 가비지 컬렉션
    del group
    gc.collect()
    
    return df, mean_features

- 어떤 피처를 기준으로 그룹화해야 예측 성능이 좋아지는지 확실히 알 수는 없다

In [84]:
# 그룹화 기준 피처 중 '상품ID'가 포함된 파생 피처명을 담을 리스트
item_mean_features = []

# ['월ID', '상품ID']로 그룹화한 월간 평균 판매량 파생 피처 생성
all_data, item_mean_features = add_mean_features(df=all_data,
                                                 mean_features=item_mean_features,
                                                 idx_features=['월ID', '상품ID'])

# ['월ID', '상품ID', '도시']로 그룹화한 월간 평균 판매량 파생 피처 생성
all_data, item_mean_features = add_mean_features(df=all_data,
                                                 mean_features=item_mean_features,
                                                 idx_features=['월ID', '상품ID', '도시'])

In [85]:
item_mean_features

['상품ID별 평균 판매량', '상품ID 도시별 평균 판매량']

In [86]:
# 그룹화 기준 피처 중 '상점ID'가 포함된 파생 피처명을 담을 리스트
shop_mean_features = []

# ['월ID', '상점ID', '상품분류ID']로 그룹화한 월간 평균 판매량 파생 피처 생성
all_data, shop_mean_features = add_mean_features(df=all_data, 
                                                 mean_features=shop_mean_features,
                                                 idx_features=['월ID', '상점ID', '상품분류ID'])

In [87]:
shop_mean_features

['상점ID 상품분류ID별 평균 판매량']

### 5-1. 시차 피처 생성 원리 및 함수 구현

- 지금까지 만든 기준 피처별 월간 평균 판매량 피처는 다음과 같다.
    1. {상품ID}별 평균 판매량
    2. {상품ID + 도시}별 평균 판매량
    3. {상품ID + 상품범주ID}별 평균 판매량
- 이제 이 세 징검다리 피처를 활용해 시차 피처를 구해보겠다.

<br>

- ✨ <u>**시차 피처는 시계열 문제에서 자주 사용하는 파생 피처**</u> ✨
    - 현시점 데이터에 과거 시점 데이터를 추가한다는 개념
    - 과거 시점 데이터는 향후 판매량 예측에 유용
    - 시차 피처는 한 달 전, 두 달 전, 세 달 전 등 원하는 시점까지 생성 가능
    
<br>

- `add_lag_features()`는 방금 설명한 원리를 적용해 만든 시차 피처를 추가하는 함수
- 파라미터는 다음과 같다
    - `df`: 원본 데이터
    - `lag_feature_to_clip`: '값의 범위를 0 ~ 20 사이로 제한할 피처'fmf ekadmf fltmxm
    - `idx_feature`: 기준 피처
    - `lag_feature`: 시차를 만들 피처
    - `nlags`: 시차
        - 1: 한 달 전 시차 피처만 생성
        - 2: 한 달 전, 두 달 전 시차 피처 생성
        - 3: 한 달 전, 두 달 전, 세 달 전 시차 피처를 모두 생성
    - `clip`: 새로 만든 시차 피처를 `lag_features_to_clip` 리스트에 저장할지 여부

In [88]:
def add_lag_features(df, lag_features_to_clip, idx_features, 
                     lag_feature, nlags=3, clip=False):
    # 시차 피처 생성에 필요한 DataFrame 부분만 복사 
    df_temp = df[idx_features + [lag_feature]].copy() 

    # 시차 피처 생성 
    for i in range(1, nlags+1):
        # 시차 피처명 
        lag_feature_name = lag_feature +'_시차' + str(i)
        # df_temp 열 이름 설정 
        df_temp.columns = idx_features + [lag_feature_name]
        # df_temp의 date_block_num 피처에 1 더하기 
        df_temp['월ID'] += 1
        # idx_feature를 기준으로 df와 df_temp 병합하기 
        df = df.merge(df_temp.drop_duplicates(), 
                      on=idx_features, 
                      how='left')
        # 결측값 0으로 대체 
        df[lag_feature_name] = df[lag_feature_name].fillna(0)
        # 0 ~ 20 사이로 제한할 시차 피처명을 lag_features_to_clip에 추가 
        if clip: 
            lag_features_to_clip.append(lag_feature_name)
    
    # 데이터 다운캐스팅
    df = downcast(df, False)
    # 가비지 컬렉션
    del df_temp
    gc.collect()
    
    return df, lag_features_to_clip

### 5-2. 시차 피처 생성 I : 월간 판매량

- 월ID, 상점ID, 상품ID를 기준 피처로 월간 판매량의 세 달치 시차 피처를 만들자

In [89]:
lag_features_to_clip = [] # 0 ~ 20 사이로 제한할 시차 피처명을 담을 리스트
idx_features = ['월ID', '상점ID', '상품ID'] # 기준 피처

# idx_features를 기준으로 월간 판매량의 세 달치 시차 피처 생성
all_data, lag_features_to_clip = add_lag_features(df=all_data, 
                                                  lag_features_to_clip=lag_features_to_clip,
                                                  idx_features=idx_features,
                                                  lag_feature='월간 판매량', 
                                                  nlags=3,
                                                  clip=True) # 값을 0 ~ 20 사이로 제한

In [90]:
all_data.head().T

,0,1,2,3,4
월ID,0.000000,0.000000,0.000000,0.000000,0.000000
상점ID,59.000000,59.000000,59.000000,59.000000,59.000000
상품ID,22154.000000,2552.000000,2554.000000,2555.000000,2564.000000
월간 판매량,1.000000,0.000000,0.000000,0.000000,0.000000
평균 판매가,999.000000,0.000000,0.000000,0.000000,0.000000
판매건수,1.000000,0.000000,0.000000,0.000000,0.000000
도시,30.000000,30.000000,30.000000,30.000000,30.000000
상품분류ID,37.000000,58.000000,58.000000,56.000000,59.000000
첫 판매월,0.000000,0.000000,0.000000,0.000000,0.000000
대분류,5.000000,7.000000,7.000000,7.000000,7.000000
상품ID별 평균 판매량,0.400000,0.022222,0.022222,0.044444,0.111111
상품ID 도시별 평균 판매량,1.000000,0.000000,0.000000,0.000000,0.000000
상점ID 상품분류ID별 평균 판매량,0.088496,0.000000,0.000000,0.008333,0.011976
월간 판매량_시차1,0.000000,0.000000,0.000000,0.000000,0.000000
월간 판매량_시차2,0.000000,0.000000,0.000000,0.000000,0.000000
월간 판매량_시차3,0.000000,0.000000,0.000000,0.000000,0.000000

In [91]:
lag_features_to_clip

['월간 판매량_시차1', '월간 판매량_시차2', '월간 판매량_시차3']

### 5-3. 시차 피처 생성 II : 판매건수, 평균 판매가

In [92]:
# idx_features를 기준으로 판매건수 피처의 세 달치 시차 피처 생성
all_data, lag_features_to_clip = add_lag_features(df=all_data, 
                                                  lag_features_to_clip=lag_features_to_clip,
                                                  idx_features=idx_features,
                                                  lag_feature='판매건수', 
                                                  nlags=3)

# idx_features를 기준으로 평균 판매가 피처의 세 달치 시차 피처 생성
all_data, lag_features_to_clip = add_lag_features(df=all_data, 
                                                  lag_features_to_clip=lag_features_to_clip,
                                                  idx_features=idx_features,
                                                  lag_feature='평균 판매가', 
                                                  nlags=3)

### 5-4. 시차 피처 생성 III : 평균 판매량

- 월ID, 상점ID, 상품ID를 기준 피처로 '상품ID별 평균 판매량'과 '상품ID 도시별 평균 판매량'의 시차 피처를 만들어보자

In [93]:
# idx_features를 기준으로 item_mean_features 요소별 시차 피처 생성
for item_mean_feature in item_mean_features:
    all_data, lag_features_to_clip = add_lag_features(df=all_data, 
                                                      lag_features_to_clip=lag_features_to_clip, 
                                                      idx_features=idx_features, 
                                                      lag_feature=item_mean_feature, 
                                                      nlags=3,
                                                      clip=True)
# item_mean_features 피처 제거
all_data = all_data.drop(item_mean_features, axis=1)

In [94]:
# ['월ID', '상점ID', '상품분류ID']를 기준으로 shop_mean_features 요소별 시차 피처 생성
for shop_mean_feature in shop_mean_features:
    all_data, lag_features_to_clip = add_lag_features(df=all_data,
                                                      lag_features_to_clip=lag_features_to_clip, 
                                                      idx_features=['월ID', '상점ID', '상품분류ID'], 
                                                      lag_feature=shop_mean_feature, 
                                                      nlags=3,
                                                      clip=True)
# shop_mean_features 피처 제거
all_data = all_data.drop(shop_mean_features, axis=1)

### 5-5. 시차 피처 생성 마무리 : 결측값 처리

In [95]:
# 월ID 3미만인 데이터 제거
all_data = all_data.drop(all_data[all_data['월ID'] < 3].index)

## 6. 피처 엔지니어링 VI : 기타 피처 엔지니어링

- 이제 간단히 피처 몇 개 추가 + 필요 없는 피처 

### 6-1. 기타 피처 추가

- 5개 더 추가

### 6-1-1. 월간 판매량 시차 피처들의 평균

In [96]:
all_data['월간 판매량 시차평균'] = all_data[['월간 판매량_시차1',
                                          '월간 판매량_시차2', 
                                          '월간 판매량_시차3']].mean(axis=1)

In [97]:
# 0 ~ 20 사이로 값 제한
all_data[lag_features_to_clip + ['월간 판매량', '월간 판매량 시차평균']] = all_data[lag_features_to_clip + ['월간 판매량', '월간 판매량 시차평균']].clip(0, 20)

### 6-1-2. 시차 변화량

In [98]:
all_data['시차변화량1'] = all_data['월간 판매량_시차1']/all_data['월간 판매량_시차2']
all_data['시차변화량1'] = all_data['시차변화량1'].replace([np.inf, -np.inf], 
                                                        np.nan).fillna(0)

all_data['시차변화량2'] = all_data['월간 판매량_시차2']/all_data['월간 판매량_시차3']
all_data['시차변화량2'] = all_data['시차변화량2'].replace([np.inf, -np.inf], 
                                                        np.nan).fillna(0)

### 6-1-3. 신상품 여부

In [99]:
all_data['신상여부'] = all_data['첫 판매월'] == all_data['월ID']

### 6-1-4. 첫 판매 후 경과 기간

In [100]:
all_data['첫 판매 후 기간'] = all_data['월ID'] - all_data['첫 판매월']

### 6-1-5. 월(Month)

In [101]:
all_data['월'] = all_data['월ID'] % 12

### 6-2. 필요 없는 피처 제거

In [102]:
# 첫 판매월, 평균 판매가, 판매건수 피처 제거
all_data = all_data.drop(['첫 판매월', '평균 판매가', '판매건수'], axis=1)

In [103]:
all_data = downcast(all_data, False) # 데이터 다운캐스팅

## 7. 피처 엔지니어링 VII : 마무리

In [104]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9904582 entries, 1122386 to 11026967
Data columns (total 31 columns):
 #   Column                   Dtype
---  ------                   -----
 0   월ID                      int8
 1   상점ID                     int8
 2   상품ID                     int16
 3   월간 판매량                   int8
 4   도시                       int8
 5   상품분류ID                   int8
 6   대분류                      int8
 7   월간 판매량_시차1               int8
 8   월간 판매량_시차2               int8
 9   월간 판매량_시차3               int8
 10  판매건수_시차1                 int8
 11  판매건수_시차2                 int8
 12  판매건수_시차3                 int8
 13  평균 판매가_시차1               float32
 14  평균 판매가_시차2               float32
 15  평균 판매가_시차3               float32
 16  상품ID별 평균 판매량_시차1         float32
 17  상품ID별 평균 판매량_시차2         float32
 18  상품ID별 평균 판매량_시차3         float32
 19  상품ID 도시별 평균 판매량_시차1      float32
 20  상품ID 도시별 평균 판매량_시차2      float32
 21  상품ID 도시별 평균 판매량_시차3      float32
 22  상점ID 상품분류ID별 평균 판매량_시차1  float32
 23  상점ID 상품분류ID별 평균 판매량_시차2  float32
 24  상점ID 상품분류ID별 평균 판매량_시차3  float32
 25  월간 판매량 시차평균              float32
 26  시차변화량1                   float32
 27  시차변화량2                   float32
 28  신상여부                     int8
 29  첫 판매 후 기간                int8
 30  월                        int8
dtypes: float32(15), int16(1), int8(15)
memory usage: 802.9 MB

In [105]:
# 훈련 데이터 (피처)
X_train = all_data[all_data['월ID'] < 33]
X_train = X_train.drop(['월간 판매량'], axis=1)
# 검증 데이터 (피처)
X_valid = all_data[all_data['월ID'] == 33]
X_valid = X_valid.drop(['월간 판매량'], axis=1)
# 테스트 데이터 (피처)
X_test = all_data[all_data['월ID'] == 34]
X_test = X_test.drop(['월간 판매량'], axis=1)

# 훈련 데이터 (타깃값)
y_train = all_data[all_data['월ID'] < 33]['월간 판매량']
# 검증 데이터 (타깃값)
y_valid = all_data[all_data['월ID'] == 33]['월간 판매량']

# 가비지 컬렉션
del all_data
gc.collect();

## 8. 모델 훈련 및 성능 검증

In [106]:
import lightgbm as lgb

# LightGBM 하이퍼파라미터
params = {'metric': 'rmse', 
          'num_leaves': 255,
          'learning_rate': 0.005,
          'feature_fraction': 0.75,
          'bagging_fraction': 0.75,
          'bagging_freq': 5,
          'force_col_wise': True,
          'random_state': 10}

cat_features = ['상점ID', '도시', '상품분류ID', '대분류', '월']

# LightGBM 훈련 및 검증 데이터셋
dtrain = lgb.Dataset(X_train, y_train)
dvalid = lgb.Dataset(X_valid, y_valid)
 
# LightGBM 모델 훈련
lgb_model = lgb.train(params=params,
                      train_set=dtrain,
                      num_boost_round=1500,
                      valid_sets=(dtrain, dvalid),
                      early_stopping_rounds=150,
                      categorical_feature=cat_features,
                      verbose_eval=100)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 3902
[LightGBM] [Info] Number of data points in the train set: 9452298, number of used features: 30
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 0.297707
Training until validation scores don't improve for 150 rounds
[100]	training's rmse: 1.01073	valid_1's rmse: 0.986993
[200]	training's rmse: 0.909083	valid_1's rmse: 0.922887
[300]	training's rmse: 0.857505	valid_1's rmse: 0.898233
[400]	training's rmse: 0.829175	valid_1's rmse: 0.888136
[500]	training's rmse: 0.810627	valid_1's rmse: 0.884038
[600]	training's rmse: 0.796874	valid_1's rmse: 0.882521
[700]	training's rmse: 0.786815	valid_1's rmse: 0.882318
[800]	training's rmse: 0.778893	valid_1's rmse: 0.882091
[900]	training's rmse: 0.772392	valid_1's rmse: 0.881891
[1000]	training's rmse: 0.76691	valid_1's rmse: 0.881599
[1100]	training's rmse: 0.76187	valid_1's rmse: 0.881711
Early stopping, best iteration is:
[999]	training's rmse: 0.766974	valid_1's rmse: 0.881574

## 9. 예측 및 결과 제출

In [107]:
# 예측
preds = lgb_model.predict(X_test).clip(0, 20)

# 제출 파일 생성
submission['item_cnt_month'] = preds
submission.to_csv('submission.csv', index=False)

In [108]:
del X_train, y_train, X_valid, y_valid, X_test, lgb_model, dtrain, dvalid
gc.collect();